# Generated by Django 5.0.4 on 2024-05-07 11:50

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id_ques', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False)),
                ('question_text', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': '5. Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='site/logo/')),
            ],
            options={
                'verbose_name': 'Nomia',
                'verbose_name_plural': '1. Nomia',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id_sur', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'опрос',
                'verbose_name_plural': '3. Опросы',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': '2. Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceQuestion',
            fields=[
                ('id_choice', models.AutoField(primary_key=True, serialize=False)),
                ('choice_text', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice', to='onboarding.question')),
            ],
            options={
                'verbose_name': 'варианты (вопрос)',
                'verbose_name_plural': '6. Варианты (вопрос)',
            },
        ),
        migrations.CreateModel(
            name='ChoiceSurvey',
            fields=[
                ('id_choice', models.AutoField(primary_key=True, serialize=False)),
                ('choice_text', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('survey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice', to='onboarding.survey')),
            ],
            options={
                'verbose_name': 'варианты (опрос)',
                'verbose_name_plural': '4. Варианты (опрос)',
            },
        ),
        migrations.CreateModel(
            name='UserQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.ManyToManyField(to='onboarding.choicequestion')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.question')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_question', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ответ (вопрос)',
                'verbose_name_plural': '8. Ответы (вопрос)',
            },
        ),
        migrations.CreateModel(
            name='UserSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.ManyToManyField(to='onboarding.choicesurvey')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.survey')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_survey', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ответ (опрос)',
                'verbose_name_plural': '7. Ответы (опрос)',
            },
        ),
    ]
