# Generated by Django 5.0.4 on 2024-05-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': '2. Пользователи'},
        ),
        migrations.RemoveField(
            model_name='userquestion',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usersurvey',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usersurvey',
            name='question',
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='survey',
            field=models.SlugField(default='empty', primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='userquestion',
            name='choices',
        ),
        migrations.AlterField(
            model_name='userquestion',
            name='question',
            field=models.SlugField(default='empty', primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='usersurvey',
            name='choices',
        ),
        migrations.AddField(
            model_name='userquestion',
            name='choices',
            field=models.SlugField(default='empty', unique=True),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='choices',
            field=models.SlugField(default='empty'),
        ),
    ]
